'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace CurrencyService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CurrencyConvertorSoap", [Namespace]:="http://www.webserviceX.NET/")>  _
    Partial Public Class CurrencyConvertor
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConversionRateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BL.My.MySettings.Default.BL_CurrencyService_CurrencyConvertor
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConversionRateCompleted As ConversionRateCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/ConversionRate", RequestNamespace:="http://www.webserviceX.NET/", ResponseNamespace:="http://www.webserviceX.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConversionRate(ByVal FromCurrency As Currency, ByVal ToCurrency As Currency) As Double
            Dim results() As Object = Me.Invoke("ConversionRate", New Object() {FromCurrency, ToCurrency})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConversionRateAsync(ByVal FromCurrency As Currency, ByVal ToCurrency As Currency)
            Me.ConversionRateAsync(FromCurrency, ToCurrency, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConversionRateAsync(ByVal FromCurrency As Currency, ByVal ToCurrency As Currency, ByVal userState As Object)
            If (Me.ConversionRateOperationCompleted Is Nothing) Then
                Me.ConversionRateOperationCompleted = AddressOf Me.OnConversionRateOperationCompleted
            End If
            Me.InvokeAsync("ConversionRate", New Object() {FromCurrency, ToCurrency}, Me.ConversionRateOperationCompleted, userState)
        End Sub
        
        Private Sub OnConversionRateOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConversionRateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConversionRateCompleted(Me, New ConversionRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.webserviceX.NET/")>  _
    Public Enum Currency
        
        '''<comentarios/>
        AFA
        
        '''<comentarios/>
        ALL
        
        '''<comentarios/>
        DZD
        
        '''<comentarios/>
        ARS
        
        '''<comentarios/>
        AWG
        
        '''<comentarios/>
        AUD
        
        '''<comentarios/>
        BSD
        
        '''<comentarios/>
        BHD
        
        '''<comentarios/>
        BDT
        
        '''<comentarios/>
        BBD
        
        '''<comentarios/>
        BZD
        
        '''<comentarios/>
        BMD
        
        '''<comentarios/>
        BTN
        
        '''<comentarios/>
        BOB
        
        '''<comentarios/>
        BWP
        
        '''<comentarios/>
        BRL
        
        '''<comentarios/>
        GBP
        
        '''<comentarios/>
        BND
        
        '''<comentarios/>
        BIF
        
        '''<comentarios/>
        XOF
        
        '''<comentarios/>
        XAF
        
        '''<comentarios/>
        KHR
        
        '''<comentarios/>
        CAD
        
        '''<comentarios/>
        CVE
        
        '''<comentarios/>
        KYD
        
        '''<comentarios/>
        CLP
        
        '''<comentarios/>
        CNY
        
        '''<comentarios/>
        COP
        
        '''<comentarios/>
        KMF
        
        '''<comentarios/>
        CRC
        
        '''<comentarios/>
        HRK
        
        '''<comentarios/>
        CUP
        
        '''<comentarios/>
        CYP
        
        '''<comentarios/>
        CZK
        
        '''<comentarios/>
        DKK
        
        '''<comentarios/>
        DJF
        
        '''<comentarios/>
        DOP
        
        '''<comentarios/>
        XCD
        
        '''<comentarios/>
        EGP
        
        '''<comentarios/>
        SVC
        
        '''<comentarios/>
        EEK
        
        '''<comentarios/>
        ETB
        
        '''<comentarios/>
        EUR
        
        '''<comentarios/>
        FKP
        
        '''<comentarios/>
        GMD
        
        '''<comentarios/>
        GHC
        
        '''<comentarios/>
        GIP
        
        '''<comentarios/>
        XAU
        
        '''<comentarios/>
        GTQ
        
        '''<comentarios/>
        GNF
        
        '''<comentarios/>
        GYD
        
        '''<comentarios/>
        HTG
        
        '''<comentarios/>
        HNL
        
        '''<comentarios/>
        HKD
        
        '''<comentarios/>
        HUF
        
        '''<comentarios/>
        ISK
        
        '''<comentarios/>
        INR
        
        '''<comentarios/>
        IDR
        
        '''<comentarios/>
        IQD
        
        '''<comentarios/>
        ILS
        
        '''<comentarios/>
        JMD
        
        '''<comentarios/>
        JPY
        
        '''<comentarios/>
        JOD
        
        '''<comentarios/>
        KZT
        
        '''<comentarios/>
        KES
        
        '''<comentarios/>
        KRW
        
        '''<comentarios/>
        KWD
        
        '''<comentarios/>
        LAK
        
        '''<comentarios/>
        LVL
        
        '''<comentarios/>
        LBP
        
        '''<comentarios/>
        LSL
        
        '''<comentarios/>
        LRD
        
        '''<comentarios/>
        LYD
        
        '''<comentarios/>
        LTL
        
        '''<comentarios/>
        MOP
        
        '''<comentarios/>
        MKD
        
        '''<comentarios/>
        MGF
        
        '''<comentarios/>
        MWK
        
        '''<comentarios/>
        MYR
        
        '''<comentarios/>
        MVR
        
        '''<comentarios/>
        MTL
        
        '''<comentarios/>
        MRO
        
        '''<comentarios/>
        MUR
        
        '''<comentarios/>
        MXN
        
        '''<comentarios/>
        MDL
        
        '''<comentarios/>
        MNT
        
        '''<comentarios/>
        MAD
        
        '''<comentarios/>
        MZM
        
        '''<comentarios/>
        MMK
        
        '''<comentarios/>
        NAD
        
        '''<comentarios/>
        NPR
        
        '''<comentarios/>
        ANG
        
        '''<comentarios/>
        NZD
        
        '''<comentarios/>
        NIO
        
        '''<comentarios/>
        NGN
        
        '''<comentarios/>
        KPW
        
        '''<comentarios/>
        NOK
        
        '''<comentarios/>
        OMR
        
        '''<comentarios/>
        XPF
        
        '''<comentarios/>
        PKR
        
        '''<comentarios/>
        XPD
        
        '''<comentarios/>
        PAB
        
        '''<comentarios/>
        PGK
        
        '''<comentarios/>
        PYG
        
        '''<comentarios/>
        PEN
        
        '''<comentarios/>
        PHP
        
        '''<comentarios/>
        XPT
        
        '''<comentarios/>
        PLN
        
        '''<comentarios/>
        QAR
        
        '''<comentarios/>
        ROL
        
        '''<comentarios/>
        RUB
        
        '''<comentarios/>
        WST
        
        '''<comentarios/>
        STD
        
        '''<comentarios/>
        SAR
        
        '''<comentarios/>
        SCR
        
        '''<comentarios/>
        SLL
        
        '''<comentarios/>
        XAG
        
        '''<comentarios/>
        SGD
        
        '''<comentarios/>
        SKK
        
        '''<comentarios/>
        SIT
        
        '''<comentarios/>
        SBD
        
        '''<comentarios/>
        SOS
        
        '''<comentarios/>
        ZAR
        
        '''<comentarios/>
        LKR
        
        '''<comentarios/>
        SHP
        
        '''<comentarios/>
        SDD
        
        '''<comentarios/>
        SRG
        
        '''<comentarios/>
        SZL
        
        '''<comentarios/>
        SEK
        
        '''<comentarios/>
        CHF
        
        '''<comentarios/>
        SYP
        
        '''<comentarios/>
        TWD
        
        '''<comentarios/>
        TZS
        
        '''<comentarios/>
        THB
        
        '''<comentarios/>
        TOP
        
        '''<comentarios/>
        TTD
        
        '''<comentarios/>
        TND
        
        '''<comentarios/>
        TRL
        
        '''<comentarios/>
        USD
        
        '''<comentarios/>
        AED
        
        '''<comentarios/>
        UGX
        
        '''<comentarios/>
        UAH
        
        '''<comentarios/>
        UYU
        
        '''<comentarios/>
        VUV
        
        '''<comentarios/>
        VEB
        
        '''<comentarios/>
        VND
        
        '''<comentarios/>
        YER
        
        '''<comentarios/>
        YUM
        
        '''<comentarios/>
        ZMK
        
        '''<comentarios/>
        ZWD
        
        '''<comentarios/>
        [TRY]
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub ConversionRateCompletedEventHandler(ByVal sender As Object, ByVal e As ConversionRateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConversionRateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
End Namespace
